spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dream_shops_db
    username: root
    password: Shermatov_1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
